# Generated by Django 2.1 on 2018-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Contact', models.IntegerField(blank=True, default=0, null=True)),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
