# Generated by Django 2.1 on 2018-08-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('TenantID', models.AutoField(primary_key=True, serialize=False)),
                ('TenantName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='TenantID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenants'),
        ),
    ]
