# Generated by Django 2.1 on 2018-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_auto_20180826_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
